version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/packages/test'
    schedule:
      interval: 'daily'
    versioning-strategy: increase
    open-pull-requests-limit: 25
    allow:
      - dependency-name: "@samchon/openapi"
      - dependency-name: "@nestjs/*"
      - dependency-name: "tstl"
      - dependency-name: "typia"
      - dependency-name: ts-node
      - dependency-name: ts-patch
      - dependency-name: typescript
    groups:
      NestJS:
        patterns:
          - "@nestjs/*"
      Samchon:
        patterns:
          - "@samchon/openapi"
          - "tstl"
          - "typia"
      TypeScript:
        patterns:
          - "ts-node"
          - "ts-patch"
          - "typescript"