name: build
on: 
  push:
    paths:
      - 'src/**'
      - 'test/**'
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: test
        working-directory: ./test
        run: npm start

      - name: migrate
        working-directory: ./packages/migrate
        run: pnpm install && npm run build && npm run test
