name: build
on: [push, pull_request]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # - name: test
      #   working-directory: ./test
      #   run: npm start

      - name: migrate
        working-directory: ./packages/migrate
        run: npm install && npm run build && npm run test